---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.15
  commands:
  - go test -coverprofile=cover.out -v ./...
  - go tool cover -func=cover.out
  when:
    event:
    - pull_request
    - push
    - tag

- name: build
  image: golang:1.15
  commands:
  - sh scripts/build.sh
  when:
    event:
    - pull_request
    - push
    - tag

- name: publish_amd64_dry_run
  image: plugins/docker:18
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.amd64
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish_arm64_dry_run
  image: plugins/docker:18
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.arm64
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish_amd64
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

- name: publish_arm64
  image: plugins/docker:18
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master
---
kind: signature
hmac: e2504063cc9d3a616b44668ce2352d5f364b543a3daef09bb282601f9e24d182

...
