---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.12
  commands:
  - go test -v ./...
  - sh scripts/build.sh
  when:
    event:
    - pull_request
    - push
    - tag

- name: publish_dry_run
  image: plugins/docker:18
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.amd64
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker:18
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master

---
kind: secret
name: docker_password
data: ODs/NQbyVO3MWs4rFbj2qcYQmaoMAW9tnJPEfs5gmwKTQF6K8hHvOV0Nej/oFTmlU8TVwg==

---
kind: secret
name: docker_username
data: ta1MaBGfEUop+p+izOnIl7thF6RQ62CGk5C0Af44msGeGiy8/MGcZ4Toyt3feOcF
