---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.15
  commands:
  - go test -coverprofile=cover.out -v ./...
  - go tool cover -func=cover.out
  when:
    event:
    - pull_request
    - push
    - tag

- name: build
  image: golang:1.15
  commands:
  - sh scripts/build.sh
  when:
    event:
    - pull_request
    - push
    - tag

- name: publish_amd64_dry_run
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: dockerhub_username_pr
    password:
      from_secret: dockerhub_password_pr
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish_arm64_dry_run
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.arm64
    username:
      from_secret: dockerhub_username_pr
    password:
      from_secret: dockerhub_password_pr
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish_amd64
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

- name: publish_arm64
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master

---
kind: signature
hmac: 74eb4f8adef025306784a612ad66ef6173879c3af59e3859782a0e0911975a92

...
