---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.12
  commands:
  - go test -v ./...
  - sh scripts/build.sh
  when:
    event:
    - pull_request
    - push
    - tag

- name: publish_dry_run
  image: plugins/docker:18
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.amd64
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker:18
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master
---
kind: signature
hmac: 57028d403d222462f90e926e3d5ed7d4689ec88bd1707736f8a8c6bab7adfad0

...
