---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.15
  commands:
  - go test -coverprofile=cover.out -v ./...
  - go tool cover -func=cover.out
  when:
    event:
    - pull_request
    - push
    - tag

- name: codecov
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - cover.out
  when:
    event:
    - pull_request
    - push

- name: build
  image: golang:1.15
  commands:
  - sh scripts/build.sh
  when:
    event:
    - pull_request
    - push
    - tag

- name: publish_dry_run
  image: plugins/docker:18
  settings:
    dry_run: true
    dockerfile: docker/Dockerfile.linux.amd64
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker:18
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: meltwater/drone-convert-pathschanged
  when:
    event:
    - push
    - tag

trigger:
  branch:
  - master
---
kind: signature
hmac: 6ce420165039ac25964fe0ce2480e8232d7c57327fe5abf8652826810f17ae52

...
